runtime: go116
manual_scaling:
  instances: 1
env_variables:
  FFMPEG: "ffmpeg"
  STREAM_URL: "https://stream-url"
  CRON: "0 55 14 * * *"
  REC_TIMEOUT: "900"
  FTP: "user:password@domain/path/x/y/z"
